### Exercise 61:

###### Load the `clusters.csv` file into a DataFrame.

###### Using the `KMeans` class from the `scikit-learn` package (`random_state=42`), create a list of WCSS (*Within-Cluster Sum-of-Squares*) values for the number of clusters from `2` to `9` inclusive.

###### Requirements:

###### - calculate WCSS for each number of clusters
###### - round WCSS values to two decimal places

###### In response, print the result to the console.

In [1]:
import numpy as np
import pandas as pd

from sklearn.cluster import KMeans

df = pd.read_csv('clusters.csv')

wcss = []
for num_clus in range(2,10):
    model = KMeans(n_clusters=num_clus, random_state=42)
    model.fit(df)
    wcss.append(float(np.round(model.inertia_,2)))

print(wcss)


[4947.8, 1950.88, 1734.81, 1486.82, 1326.0, 1259.37, 972.07, 850.57]


### Exercise 62:

###### Load the `clusters.csv` file into a DataFrame.

###### The distribution of the variables from this file is shown below.

###### Using the `KMeans` class from the `scikit-learn` package, a list of WCSS (Within-Cluster Sum-of-Squares) values was calculated.

###### Using the elbow method, select the appropriate number of clusters.

###### In response, print the selected number of clusters to the console.

In [1]:
import numpy as np
import pandas as pd

from sklearn.cluster import KMeans
np.random.seed(42)

df = pd.read_csv('clusters.csv')

wcss = []
for num_clus in range(2,30):
    model = KMeans(n_clusters=num_clus, random_state=42)
    model.fit(df)
    wcss.append(round(float(model.inertia_),2))

print(wcss)


[4947.8, 1950.88, 1734.81, 1486.82, 1326.0, 1259.37, 972.07, 850.57, 796.91, 752.99, 695.04, 651.97, 607.24, 555.64, 519.58, 482.75, 464.46, 427.91, 411.03, 415.74, 388.25, 363.18, 353.41, 337.37, 322.94, 327.77, 309.26, 305.32]


### Exercise 63:

###### Load the `clusters.csv` file into a DataFrame and assign it to the `df` variable.

###### Using the `AgglomerativeClustering` class from the `scikit-learn` package, create a model to split the given dataset into two clusters.

###### Make predictions based on this model and assign a new column `'cluster'` which stores the cluster number for each sample in the `df` DataFrame.

###### In response, print the first ten rows of the `df` DataFrame to the console.

In [2]:
import numpy as np
import pandas as pd
from sklearn.cluster import AgglomerativeClustering

df = pd.read_csv('clusters.csv')

model = AgglomerativeClustering(n_clusters=2)

df['cluster'] = model.fit_predict(df)
print(df.head(10))

         x1        x2  cluster
0 -2.776333 -4.166641        0
1 -1.335879 -1.083934        0
2  6.507272 -0.158773        1
3 -0.956622  0.235036        0
4 -1.558383 -3.969630        0
5 -0.652304 -1.332604        0
6  5.560753  1.517069        1
7 -0.891052 -3.455786        0
8  6.391479  3.597473        1
9  5.812508 -0.845526        1


### Exercise 64:

###### Load the `clusters.csv` file into a DataFrame and assign it to the `df` variable.

###### Using the `AgglomerativeClustering` class from the `scikit-learn` package, create a model to split the given dataset into two clusters.

###### Use the Manhattan metric.

###### Make predictions based on this model and assign a new column `'cluster'` which stores the cluster number for each sample in the `df` DataFrame.

###### In response, print the first ten rows of the `df` DataFrame to the console.

In [3]:
import pandas as pd
from sklearn.cluster import AgglomerativeClustering

df = pd.read_csv('clusters.csv')
 
cluster = AgglomerativeClustering(
    n_clusters=2, 
    metric='manhattan', 
    linkage='complete'
)
cluster.fit_predict(df)
 
df = pd.DataFrame(df, columns=['x1', 'x2'])
df['cluster'] = cluster.labels_
 
print(df.head(10))

         x1        x2  cluster
0 -2.776333 -4.166641        0
1 -1.335879 -1.083934        0
2  6.507272 -0.158773        1
3 -0.956622  0.235036        0
4 -1.558383 -3.969630        0
5 -0.652304 -1.332604        0
6  5.560753  1.517069        1
7 -0.891052 -3.455786        0
8  6.391479  3.597473        1
9  5.812508 -0.845526        1


### Exercise 65:

###### Load the `clusters.csv` file into a DataFrame and assign it to the `df` variable.

###### Using the `DBSCAN` class from the `scikit-learn` package, create a model to split the given dataset into clusters.

###### Set the following arguments:

###### - `eps=0.6`
###### - `min_samples=7`

###### Make predictions based on this model and assign a new column `'cluster'` which stores the cluster number for each sample in the `df` DataFrame.

###### In response, print the first ten rows of the `df` DataFrame.

In [4]:
import pandas as pd
from sklearn.cluster import DBSCAN

df = pd.read_csv('clusters.csv')

model = DBSCAN(eps=0.6, min_samples=7)

df['cluster'] = model.fit_predict(df)
print(df.head(10))

         x1        x2  cluster
0 -2.776333 -4.166641        0
1 -1.335879 -1.083934        0
2  6.507272 -0.158773        1
3 -0.956622  0.235036        0
4 -1.558383 -3.969630        0
5 -0.652304 -1.332604        0
6  5.560753  1.517069        1
7 -0.891052 -3.455786        0
8  6.391479  3.597473       -1
9  5.812508 -0.845526        1


### Exercise 66:

###### Load the `clusters.csv` file into a DataFrame and assign it to the `df` variable.

###### Using the `DBSCAN` class from the `scikit-learn` package, create a model to split the given dataset into clusters.

###### Set the following arguments:

###### - `eps = 0.6`
###### - `min_samples = 7`

###### Make predictions based on this model and assign a new column `'cluster'` which stores the cluster number for each sample in the `df` DataFrame.

In [1]:
import pandas as pd
from sklearn.cluster import DBSCAN

df = pd.read_csv('clusters.csv')

model = DBSCAN(eps=0.6, min_samples=7)

model.fit_predict(df)
df['cluster'] = model.labels_

print(df['cluster'].value_counts())

cluster
 0    647
 1    318
-1     35
Name: count, dtype: int64


### Exercise 67:

###### Load the `pca.csv` file into the `df` DataFrame. This file contains three explanatory variables (`var1`, `var2`, `var3`) and a class variable.

###### Extract the following:

###### - `var1`, `var2`, `var3` → assign to variable `X`
###### - `class` → assign to variable `y`

###### Then, using the `StandardScaler` class, standardize `X` and assign the result to `X_std`.

###### In response, print the first ten rows of the `X_std` array to the console.

In [2]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler

np.random.seed(42)
df = pd.read_csv('pca.csv')

scaler = StandardScaler()

X = df.drop('class',axis=1)
y = df['class']

X_std = scaler.fit_transform(X)
print(X_std[:10])

[[-0.90068117 -1.34022653 -1.3154443 ]
 [-1.14301691 -1.34022653 -1.3154443 ]
 [-1.38535265 -1.39706395 -1.3154443 ]
 [-1.50652052 -1.2833891  -1.3154443 ]
 [-1.02184904 -1.34022653 -1.3154443 ]
 [-0.53717756 -1.16971425 -1.05217993]
 [-1.50652052 -1.34022653 -1.18381211]
 [-1.02184904 -1.2833891  -1.3154443 ]
 [-1.74885626 -1.34022653 -1.3154443 ]
 [-1.14301691 -1.2833891  -1.44707648]]


### Exercise 68:

###### The `pca.csv` file was loaded into the `df` DataFrame. Using the `StandardScaler` class, the variables in `X` were standardized and assigned to `X_std`.

###### Implement the PCA algorithm using the `X_std` array. Reduce the result to two principal components and assign it to `X_pca`.

###### In response, print the first ten rows of the `X_pca` array.

###### Steps:

###### 1. Compute the covariance matrix of the `X_std` array  
###### 2. Find the eigenvectors and their corresponding eigenvalues for this covariance matrix  
###### 3. Sort eigenvectors by decreasing eigenvalues  
###### 4. Determine the number of components (in this case 2)  
###### 5. Create matrix `W` from selected vectors (columns as eigenvectors)  
###### 6. Multiply `X_std` by `W` and assign to the `X_pca` variable

In [3]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler


np.random.seed(42)
df = pd.read_csv('pca.csv')

X = df.copy()
y = X.pop('class')

scaler = StandardScaler()
X_std = scaler.fit_transform(X)

eig_vals, eig_vecs = np.linalg.eig(np.cov(X_std, rowvar=False))
eig_pairs = [
    (np.abs(eig_vals[i]), eig_vecs[:, i]) 
    for i in range(len(eig_vals))
]
eig_pairs.sort(reverse=True)
 
W = np.hstack((
    eig_pairs[0][1].reshape(3, 1), 
    eig_pairs[1][1].reshape(3, 1)
))
X_pca = X_std.dot(W)
print(X_pca[:10])


[[-2.06036006  0.2986744 ]
 [-2.1959812   0.10172707]
 [-2.36522102 -0.08074913]
 [-2.36579421 -0.20816508]
 [-2.12817063  0.20020073]
 [-1.60325585  0.4127035 ]
 [-2.32300467 -0.26268319]
 [-2.09455194  0.1857296 ]
 [-2.53503403 -0.39064128]
 [-2.23877073  0.15624518]]


### Exercise 69:

###### The PCA algorithm was implemented using the `X_std` array and the result was assigned to the `X_pca` variable.

###### Create a DataFrame called `df_pca` using the `X_pca` array and the `y` variable.

###### In response, print the first ten rows of the `df_pca` object to the console.

In [1]:
import numpy as np
import pandas as pd

from sklearn.preprocessing import StandardScaler

np.random.seed(42)

df = pd.read_csv('pca.csv')
X = df.drop('class', axis=1)
y = df['class']

scaler = StandardScaler()
X_std = scaler.fit_transform(X)

eig_vals, eig_vecs = np.linalg.eig(np.cov(X_std,rowvar=False))
eig_pairs = [ (np.abs(eig_vals[i]), eig_vecs[:,i]) for i in range (len(eig_vals))]
eig_pairs.sort(reverse=True)

W = np.hstack((eig_pairs[0][1].reshape(3,1),eig_pairs[1][1].reshape(3,1)))
X_pca = X_std.dot(W)

df_pca = pd.DataFrame(X_pca, columns=['pca_1', 'pca_2'])
df_pca['pca_2'] = - df_pca['pca_2']
df_pca ['class'] = y
print(df_pca.head(10))


      pca_1     pca_2  class
0 -2.060360 -0.298674    0.0
1 -2.195981 -0.101727    0.0
2 -2.365221  0.080749    0.0
3 -2.365794  0.208165    0.0
4 -2.128171 -0.200201    0.0
5 -1.603256 -0.412703    0.0
6 -2.323005  0.262683    0.0
7 -2.094552 -0.185730    0.0
8 -2.535034  0.390641    0.0
9 -2.238771 -0.156245    0.0
