### Exercise 41:

###### The following `df` DataFrame is given:

|    | var1 |
|---:|------:|
| 0 | 1.161966 |
| 1 | 0.251008 |
| 2 | 0.948663 |
| 3 | -0.141041 |
| 4 | 0.978152 |
| 5 | 0.496576 |
| 6 | -0.006001 |
| 7 | -0.350019 |
| 8 | -0.693200 |
| 9 | -2.422743 |

###### Implement the `sigmoid()` function using the `numpy` package.

###### Using the implemented function, calculate sigmoid values for the variable `var1` and assign them to the new column `'var1_sigmoid'`.

###### In response, print the `df` DataFrame to the console.

In [1]:
import numpy as np
import pandas as pd

np.random.seed(42)
df = pd.DataFrame(data=np.random.randn(10), columns=['var1'])

df['var1_sigmoid'] = 1/(1+np.exp(-df['var1']))
print(df)


       var1  var1_sigmoid
0  0.496714      0.621687
1 -0.138264      0.465489
2  0.647689      0.656489
3  1.523030      0.820984
4 -0.234153      0.441728
5 -0.234137      0.441732
6  1.579213      0.829093
7  0.767435      0.682966
8 -0.469474      0.384741
9  0.542560      0.632408


### Exercise 42:

###### Load the `data2.csv` file into the DataFrame.

###### Then, using the `StandardScaler` class from the `scikit-learn` package, standardize all the variables.

###### In response, print the result to the console.

In [1]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

df = pd.read_csv('data2.csv')
scaler = StandardScaler()

df = scaler.fit_transform(df)
print(df)

[[-4.78538093e-01 -2.13716784e-01 -4.58354726e-01 -5.11379891e-01
   6.35712510e-02]
 [ 1.37424404e+00  3.89500006e-01  1.29239853e+00  1.40549685e+00
  -6.15973560e-01]
 [ 3.77693525e-01 -1.78382691e-02  3.90457896e-01  2.78322453e-01
   7.42405241e-01]
 [-4.98583649e-01 -4.18498868e-01 -4.42704615e-01 -5.53083273e-01
   4.72293287e-01]
 [-7.44857626e-01 -1.13968795e+00 -7.23582930e-01 -7.45037138e-01
   7.70768487e-02]
 [ 1.84961008e+00  2.17466556e+00  1.97194284e+00  1.80478455e+00
   1.35371124e+00]
 [ 2.25338486e+00  5.20827647e-01  2.26435282e+00  2.44660256e+00
   5.36267170e-01]
 [ 9.81923864e-01 -1.00390852e+00  9.38211795e-01  8.88197447e-01
  -2.03056189e-02]
 [-2.29400465e-01 -8.23611251e-01 -2.35958406e-01 -3.98692028e-01
   6.42890310e-01]
 [-6.90360146e-02 -6.54443443e-01 -1.33820837e-01 -1.63851706e-01
  -2.16627401e+00]
 [-2.66627926e-01  1.26650154e+00 -3.34389370e-01 -3.45749436e-01
  -7.70932523e-01]
 [ 7.55695443e-01 -1.69198940e-01  7.03460124e-01  6.84708603e-01

### Exercise 43:

###### Load `X_train.csv` and `X_test.csv` files respectively into DataFrames named `X_train` and `X_test`.

###### Then use the `StandardScaler` class from the `scikit-learn` package to standardize the data.

###### Fit the scaler on the `X_train` dataset.

###### In response, print the first five rows of `X_train` and `X_test` to the console.

In [2]:
import pandas as pd
from sklearn.preprocessing import StandardScaler

X_train = pd.read_csv('X_train.csv')
X_test = pd.read_csv('X_test.csv')

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train[:5])
print(X_test[:5])

[[-0.34913849 -1.43851335 -0.41172595 -0.39047943 -1.86366229]
 [-0.20468665  0.31264011 -0.13367256 -0.27587995  1.07807258]
 [-0.32931176 -0.21507235 -0.31739376 -0.36435749 -1.57987983]
 [ 1.02740257  2.08982423  1.04692153  0.91758377  0.31630299]
 [ 1.82896865  0.69600073  1.76368137  1.78382103 -0.33367351]]
[[-0.46809882 -0.14171322 -0.44468042 -0.485979    0.29337107]
 [ 1.36445686  0.49958757  1.30643802  1.3344113  -0.39171992]
 [ 0.37878549  0.06653205  0.40430925  0.26397349  0.97774544]
 [-0.48792555 -0.35942419 -0.42902705 -0.52558323  0.70542894]
 [-0.731511   -1.12614544 -0.70996395 -0.70787505  0.3069869 ]]


### Exercise 44:

###### Implement the `entropy()` function using the `numpy` package.

###### Round the result to four decimal places.

###### Then the following `df` DataFrame is given:

|    | val_1 | val_2 |
|---:|------:|------:|
| 0 | 0.01 | 0.99 |
| 1 | 0.11 | 0.89 |
| 2 | 0.21 | 0.79 |
| 3 | 0.31 | 0.69 |
| 4 | 0.41 | 0.59 |
| 5 | 0.51 | 0.49 |
| 6 | 0.61 | 0.39 |
| 7 | 0.71 | 0.29 |
| 8 | 0.81 | 0.19 |
| 9 | 0.91 | 0.09 |

###### Using the implemented function, calculate the entropy for each pair in this DataFrame and assign it to the `'entropy'` column.

###### In response, print the `df` DataFrame to the console.

In [3]:
import numpy as np
import pandas as pd

data_dict = {
    'val_1': np.arange(0.01, 1.0, 0.1), 
    'val_2': 1 - np.arange(0.01, 1.0, 0.1)
}
df = pd.DataFrame(data_dict)

def entropy(x):
    return np.round(-np.sum(x*np.log2(x)),4)

df['entropy'] = df.apply(entropy, axis=1)
print(df)


   val_1  val_2  entropy
0   0.01   0.99   0.0808
1   0.11   0.89   0.4999
2   0.21   0.79   0.7415
3   0.31   0.69   0.8932
4   0.41   0.59   0.9765
5   0.51   0.49   0.9997
6   0.61   0.39   0.9648
7   0.71   0.29   0.8687
8   0.81   0.19   0.7015
9   0.91   0.09   0.4365


### Exercise 45:

###### The `predictions.csv` file contains predictions based on a multi-class classification model (3 classes).

###### - `y_true` column → actual values  
###### - `y_pred` column → values predicted by the model  

###### Using the `accuracy_score()` function from the `scikit-learn` package, calculate the accuracy of this model.

###### In response, print the accuracy rounded to four decimal places to the console as shown below.

In [1]:
import numpy as np
import pandas as pd
from sklearn.metrics import accuracy_score
 
 
df = pd.read_csv('predictions.csv')
acc = accuracy_score(df['y_true'],df['y_pred'])
print(f'Accuracy: {acc:.4f}')


Accuracy: 0.7241


### Exercise 46:

###### The `predictions.csv` file contains predictions based on a multi-class classification model (3 classes).

###### - `y_true` column → actual values  
###### - `y_pred` column → values predicted by the model  

###### Use the `confusion_matrix()` function from the `scikit-learn` package to calculate the confusion matrix and print it to the console.

In [3]:
import pandas as pd
from sklearn.metrics import confusion_matrix

df = pd.read_csv('predictions.csv')
print(confusion_matrix(df['y_true'], df['y_pred']))

[[ 6  1  0]
 [ 3 10  2]
 [ 0  2  5]]


### Exercise 47:

###### The following arrays are given:

###### - `X_train`, `y_train`
###### - `X_test`, `y_test`

###### Using the `DecisionTreeClassifier` class from the `scikit-learn` package, create a classification model (leave the default arguments).

###### Train the model on the training set and evaluate it on the test set.

###### In response, print the model accuracy (up to four decimal places) to the console as shown below.

In [10]:
import numpy as np
import pandas as pd

from sklearn.datasets import make_moons
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier


np.random.seed(42)
raw_data = make_moons(n_samples=2000, noise=0.25, random_state=42)
data = raw_data[0]
target = raw_data[1]

X_train, X_test, y_train, y_test = train_test_split(data, target)

model = DecisionTreeClassifier()
model.fit(X_train, y_train)

print(f'Accuracy: {model.score(X_test, y_test):.4f}')

Accuracy: 0.9020


### Exercise 48:

###### The following arrays are given:

###### - `X_train`, `y_train`
###### - `X_test`, `y_test`

###### Using the `DecisionTreeClassifier` class from the `scikit-learn` package, create a classification model (`max_depth=6`).

###### Train the model on the training set and evaluate it on the test set.

###### In response, print the model accuracy (up to four decimal places) to the console as shown below.